services:
  db:
    image: postgres:13.14
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: paradigmas
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
